import "./styles/globals.scss";

import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google";
import Header from "./components/Header/Header";

const interTight = Inter_Tight({
  subsets: ["latin"],
  variable: "--font-inter-tight",
});

export const metadata: Metadata = {
  title: "Geferson Lopes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${interTight.variable} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
